version: "3"

tasks:
  build-plugins:
    desc: Build example plugins
    dir: ./example-plugins
    cmds:
      - cd helloworld/cmd/hello && go build -buildmode=plugin
      - cd helloworld/cmd/howdy && go build -buildmode=plugin
      - cd todo-api && go build -buildmode=plugin
      - cd fallback && go build -buildmode=plugin
